server.port=7491

# -----------------------------------------
# spring国际化的使用，用来通过错误码映射得到错误说明
# -----------------------------------------
spring.messages.basename = i18n/ResultCode


# -----------------------------------------
# dataSource1
# -----------------------------------------
spring.datasource.primary.url=jdbc:mysql://127.0.0.1:3306/yanhuohui-batch?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=GMT%2B8
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.primary.username=root
spring.datasource.primary.password=123456
spring.datasource.primary.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.primary.hikari.pool-name=HikariCP-Primary
spring.datasource.primary.hikari.minimum-idle=5
spring.datasource.primary.hikari.idle-timeout=600000
spring.datasource.primary.hikari.maximum-pool-size=10
spring.datasource.primary.hikari.max-lifetime=1800000
spring.datasource.primary.hikari.connection-timeout=30000
spring.datasource.primary.hikari.connection-test-query=SELECT 1
# -----------------------------------------
# dataSource2
# -----------------------------------------
spring.datasource.wangdai.url=jdbc:mysql://127.0.0.1:3306/yanhuohui-batch-wangdai?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=GMT%2B8
spring.datasource.wangdai.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.wangdai.username=root
spring.datasource.wangdai.password=123456
spring.datasource.wangdai.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.wangdai.hikari.pool-name=HikariCP-Secondary
spring.datasource.wangdai.hikari.minimum-idle=5
spring.datasource.wangdai.hikari.idle-timeout=600000
spring.datasource.wangdai.hikari.maximum-pool-size=10
spring.datasource.wangdai.hikari.max-lifetime=1800000
spring.datasource.wangdai.hikari.connection-timeout=30000
spring.datasource.wangdai.hikari.connection-test-query=SELECT 1

#查询数据库打印SQL和参数
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true 
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE

#项目启动时的建表sql脚本,该脚本由Spring Batch提供
spring.datasource.schema=classpath:/org/springframework/batch/core/schema-mysql.sql
#在项目启动时进行执行建表sql
#是否生成执行状态记录的表结构
spring.batch.initialize-schema=always
#禁止Spring Batch自动执行,既需要用户触发才能执行
spring.batch.job.enabled=false

spring.main.allow-bean-definition-overriding=true

#使实体类Entity不进行懒加载，也可以在实体类上直接加注解@Proxy(lazy=false)进行更细粒度的控制
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.transaction=DEBUG

###xxljob的配置
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin
### xxl-job, access token
xxl.job.admin.accessToken=default_token
### xxl-job timeout by second, default 3s
xxl.job.admin.timeout=3

### xxl-job executor appname
xxl.job.executor.appname=xxl-job-executor-sample
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
xxl.job.executor.address=
### xxl-job executor server-info
xxl.job.executor.ip=
### ????????
xxl.job.executor.port=9999
### xxl-job executor log-path
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
### xxl-job executor log-retention-days
xxl.job.executor.logretentiondays=30

